## Lecture 8 Homework

In [7]:
# packages in the notebook 

import pandas as pd # Package to work with data

import numpy as np # Numerical analysis package

In [2]:
# Data in jupyter notebook uses the function "read_csv" to read data. This is in pandas

# df = pd.read_csv('data.csv')

In [8]:
# you can also use github to import data, all you need to add is the raw data url

df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/PUBH1142Chap0801.csv')

In [10]:
# type of dataframe

type(df)

pandas.core.frame.DataFrame

In [15]:
# the function "dir" prints out the methods and attributes of the data

dir(df)[:20]

['Age',
 'CholesterolAfter',
 'CholesterolBefore',
 'DOB',
 'Delta',
 'Group',
 'HR',
 'Name',
 'Smoke',
 'Survey',
 'T',
 'TAG',
 'Vocation',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__']

In [18]:
# the "head" function will print the first 5 rows of the dataframe 

df.head()

Name         DOB  Age               Vocation  Smoke  HR  sBP  \
0       Dylan Patton  1981-10-07   43         Energy manager      0  47  145   
1      Sandra Howard  1993-01-27   53            Tax adviser      0  51  115   
2  Samantha Williams  1973-12-21   33          IT consultant      0  54  120   
3     Ashley Hensley  1981-12-01   43      Nurse, children's      0  54  103   
4      Robert Wilson  1964-06-23   46  Clinical embryologist      0  61  138   

   CholesterolBefore  TAG  Survey  CholesterolAfter  Delta   Group  
0                1.2  1.2       1               0.7    0.5  Active  
1                1.2  0.6       3               1.0    0.2  Active  
2                2.0  1.3       3               1.7    0.3  Active  
3                2.1  1.6       4               2.1    0.0  Active  
4                2.8  2.1       5               2.8    0.0  Active

In [19]:
# the "shape" attribute will show the number of rows and columns 
# it's an attribute so no need for the parenthsis 
# the shape attribute will return a tuple 

df.shape

(200, 13)

In [21]:
# print out the columns

df.columns

Index(['Name', 'DOB', 'Age', 'Vocation', 'Smoke', 'HR', 'sBP',
       'CholesterolBefore', 'TAG', 'Survey', 'CholesterolAfter', 'Delta',
       'Group'],
      dtype='object')

In [22]:
# print out the dimensions of the data

df.ndim

2

In [23]:
# print the size of the dataframe or the total number of data points

df.size

2600

In [24]:
# the dtype attribute will return all the data types of the values in each column 
# SUPER IMPORTANT STEP because this will help you clean up data
# catagorical variables are denoted as "object" types
df.dtypes

Name                  object
DOB                   object
Age                    int64
Vocation              object
Smoke                  int64
HR                     int64
sBP                    int64
CholesterolBefore    float64
TAG                  float64
Survey                 int64
CholesterolAfter     float64
Delta                float64
Group                 object
dtype: object

In [25]:
# now you have all the information and data, but what if you want to look at a specific row or column?
# extract one column

age_column = df['Age']

In [27]:
age_column = df.Age
age_column.head()

0    43
1    53
2    33
3    43
4    46
Name: Age, dtype: int64

In [28]:
age = age_column.to_numpy()

In [32]:
# an array is like a list on steroids, there is so much you can do 
type(age)
age

array([43, 53, 33, 43, 46, 48, 54, 58, 44, 31, 45, 35, 49, 56, 57, 38, 35,
       50, 45, 49, 63, 45, 51, 43, 31, 58, 40, 47, 45, 41, 47, 38, 54, 30,
       46, 64, 41, 40, 45, 65, 74, 55, 58, 53, 68, 54, 72, 32, 38, 59, 53,
       69, 42, 67, 38, 51, 37, 36, 34, 38, 31, 48, 49, 62, 39, 74, 41, 42,
       60, 67, 42, 74, 52, 37, 61, 54, 72, 36, 49, 47, 49, 49, 69, 43, 38,
       60, 45, 71, 65, 73, 60, 70, 45, 49, 65, 53, 30, 58, 50, 69, 72, 61,
       33, 30, 44, 71, 49, 75, 43, 35, 55, 38, 36, 46, 60, 40, 57, 69, 56,
       66, 60, 42, 49, 68, 32, 31, 56, 35, 63, 54, 68, 72, 40, 41, 66, 73,
       36, 54, 57, 74, 48, 72, 54, 71, 42, 54, 66, 58, 60, 63, 44, 55, 73,
       55, 40, 43, 71, 54, 61, 55, 67, 55, 68, 71, 54, 42, 53, 69, 57, 45,
       62, 33, 74, 74, 64, 43, 35, 57, 64, 55, 74, 50, 40, 62, 65, 63, 68,
       45, 41, 54, 62, 65, 72, 61, 70, 66, 54, 61, 65, 66])

In [33]:
# calculate the average of the column using "mean" funtion
age_column.mean()

53.07

In [34]:
age_column.describe()

count    200.000000
mean      53.070000
std       12.553207
min       30.000000
25%       43.000000
50%       54.000000
75%       64.000000
max       75.000000
Name: Age, dtype: float64

In [35]:
# idoc is integer location, it will show the data for a specific index
df.iloc[0]

Name                   Dylan Patton
DOB                      1981-10-07
Age                              43
Vocation             Energy manager
Smoke                             0
HR                               47
sBP                             145
CholesterolBefore               1.2
TAG                             1.2
Survey                            1
CholesterolAfter                0.7
Delta                           0.5
Group                        Active
Name: 0, dtype: object

In [37]:
df.iloc[[1, 4, 6]]

Name         DOB  Age               Vocation  Smoke  HR  sBP  \
1    Sandra Howard  1993-01-27   53            Tax adviser      0  51  115   
4    Robert Wilson  1964-06-23   46  Clinical embryologist      0  61  138   
6  Frank Zimmerman  1981-03-04   54         Police officer      0  60  129   

   CholesterolBefore  TAG  Survey  CholesterolAfter  Delta   Group  
1                1.2  0.6       3               1.0    0.2  Active  
4                2.8  2.1       5               2.8    0.0  Active  
6                2.9  2.4       1               2.6    0.3  Active

In [42]:
df.iloc[:20]

Name         DOB  Age                          Vocation  \
0        Dylan Patton  1981-10-07   43                    Energy manager   
1       Sandra Howard  1993-01-27   53                       Tax adviser   
2   Samantha Williams  1973-12-21   33                     IT consultant   
3      Ashley Hensley  1981-12-01   43                 Nurse, children's   
4       Robert Wilson  1964-06-23   46             Clinical embryologist   
5         Leslie Diaz  1994-08-25   48            Politician's assistant   
6     Frank Zimmerman  1981-03-04   54                    Police officer   
7        Aaron Harris  1948-01-10   58                 Nurse, children's   
8       William Smith  1998-11-20   44  Scientific laboratory technician   
9     Andrea Fletcher  1955-12-23   31                     Lexicographer   
10        James Wells  1998-08-09   45                Charity fundraiser   
11         Lisa Perez  1983-09-05   35           Chief Marketing Officer   
12   Desiree Sandoval  1981-11-08   49                       Hydrologist   
13       Karen Knight  1941-06-14   56       Advertising account planner   
14       Evan Stewart  1934-12-22   57                      Web designer   
15       Mark Johnson  1958-11-22   38                          Lobbyist   
16         Roger Chen  1985-11-19   35                      Photographer   
17     Dennis Sanchez  1945-10-25   50           Chartered loss adjuster   
18       Eric Hendrix  1969-05-04   45       Community education officer   
19   Kathleen Burnett  1970-03-23   49            Occupational hygienist   

    Smoke  HR  sBP  CholesterolBefore  TAG  Survey  CholesterolAfter  Delta  \
0       0  47  145                1.2  1.2       1               0.7    0.5   
1       0  51  115                1.2  0.6       3               1.0    0.2   
2       0  54  120                2.0  1.3       3               1.7    0.3   
3       0  54  103                2.1  1.6       4               2.1    0.0   
4       0  61  138                2.8  2.1       5               2.8    0.0   
5       0  59  122                2.8  1.4       4               2.6    0.2   
6       0  60  129                2.9  2.4       1               2.6    0.3   
7       0  61  131                3.1  2.2       1               2.9    0.2   
8       0  58  111                3.1  2.4       1               2.8    0.3   
9       0  59  122                3.2  1.7       5               2.8    0.4   
10      0  62  121                3.2  1.7       4               2.7    0.5   
11      0  61  119                3.3  2.0       3               2.9    0.4   
12      0  61  135                3.3  2.3       5               3.1    0.2   
13      0  62  134                3.4  2.1       2               3.3    0.1   
14      0  75  162                3.5  2.4       3               3.4    0.1   
15      2  62  140                3.5  2.6       1               2.9    0.6   
16      0  59  121                3.5  2.3       2               3.4    0.1   
17      0  63  129                3.5  2.5       1               3.5    0.0   
18      2  61  138                3.6  2.3       1               3.2    0.4   
19      0  64  144                3.7  2.2       1               3.7    0.0   

      Group  
0    Active  
1    Active  
2    Active  
3    Active  
4    Active  
5    Active  
6    Active  
7    Active  
8   Control  
9    Active  
10   Active  
11   Active  
12   Active  
13  Control  
14   Active  
15   Active  
16  Control  
17   Active  
18  Control  
19   Active

In [51]:
df.iloc[:5, [0, 3]]

Name               Vocation
0       Dylan Patton         Energy manager
1      Sandra Howard            Tax adviser
2  Samantha Williams          IT consultant
3     Ashley Hensley      Nurse, children's
4      Robert Wilson  Clinical embryologist

In [52]:
# when you want to filter data
# use the "unique" function to find all the values that are in a specic column
df.Smoke.unique()

array([0, 2, 1])

In [53]:
age_nonsmokers = df.loc[df.Smoke == 0]['Age'].to_numpy()
age_nonsmokers

array([43, 53, 33, 43, 46, 48, 54, 58, 44, 31, 45, 35, 49, 56, 57, 35, 50,
       49, 63, 45, 51, 40, 47, 41, 47, 38, 54, 30, 46, 64, 40, 45, 65, 55,
       53, 54, 72, 32, 38, 59, 53, 42, 38, 51, 37, 36, 48, 49, 62, 39, 74,
       42, 72, 61, 33, 30, 44, 71, 49, 75, 43, 55, 38, 36, 46, 60, 57, 69,
       56, 66, 60, 42, 32, 31, 56, 35, 63, 54, 68, 72, 40, 54, 62, 74, 62,
       41, 61, 61])

In [54]:
age_smokers = df.loc[df.Smoke == 2]['Age'].to_numpy()
age_smokers

array([38, 45, 43, 31, 58, 45, 74, 58, 67, 60, 49, 71, 60, 49, 35, 40, 49,
       68, 36, 72, 54, 63, 55, 61, 71, 45, 35])

In [56]:
print(age_nonsmokers.mean())
print(age_smokers.mean())

50.09090909090909
53.03703703703704
